version: "3.9"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend:v1
    env_file:
      - ./backend/.env
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
